version: '3.8'

services:
  # Laravel Application
  app:
    image: php:8.1-fpm
    container_name: php
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    networks:
      - laravel
    environment:
      - PUID=1000
      - PGID=1000
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=Netflix
      - DB_USERNAME=root
      - DB_PASSWORD=qwerty
    depends_on:
      - mariadb
    ports:
      - "9000:9000"

  # MariaDB
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_DATABASE: Netflix
      MYSQL_ROOT_PASSWORD: qwerty
    ports:
      - "3306:3306"
    networks:
      - laravel
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    restart: always

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - mariadb
    networks:
      - laravel

  # Nginx Server
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    networks:
      - laravel
    depends_on:
      - app

networks:
  laravel:
