version: "3.9"

services:
  mariadb:
    image: mariadb:11
    container_name: netflix-db
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: Netflix
    ports:
      - "3306:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

  laravel:
    build:
      context: .
      dockerfile: ./netflix-api/Dockerfile
    container_name: netflix-api
    ports:
      - "8000:8000"
    volumes:
      - ./netflix-api:/var/www/html
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_DATABASE: Netflix
      DB_USERNAME: api
      DB_PASSWORD: password
    command: >
      sh -c "/var/www/html/docker/wait-for-it.sh mariadb:3306 -- /var/www/html/docker/entrypoint.sh"    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: netflix-phpmyadmin
    restart: no
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: qwerty
    depends_on:
      - mariadb

  frontend:
    build:
      context: ./netflix_frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    restart: no
    ports:
      - "8080:8080" # Expose Vue.js frontend on port 8080
    volumes:
      - ./netflix_frontend:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable file watching in Docker
    command: npm run serve


volumes:
  db-data: