FROM php:8.2-fpm

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    openssl \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl \
    libzip-dev \
    libonig-dev \
    libxml2-dev

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl
RUN docker-php-ext-configure gd --with-freetype --with-jpeg
RUN docker-php-ext-install gd

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set working directory
WORKDIR /var/www/html

# Copy existing application directory contents
COPY . .

# Copy the docker folder
COPY ./docker /var/www/html/docker

RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html

# Make entrypoint.sh and wait-for-it.sh executable
RUN chmod +x /var/www/html/docker/entrypoint.sh && chmod +x /var/www/html/docker/wait-for-it.sh

# Expose port 8000
EXPOSE 8000

# Run the scripts
CMD [".laravel/docker/entrypoint.sh"]
CMD [".laravel/docker/wait-for-it.sh"]