-- User creation

CREATE USER 'senior'@'%' IDENTIFIED BY 'password';
GRANT SHUTDOWN, CREATE USER, RELOAD ON *.* TO 'senior'@'%';
GRANT CREATE ROUTINE, CREATE, SELECT, EXECUTE, DELETE, CREATE VIEW, ALTER ROUTINE, INDEX, EVENT,
    INSERT, LOCK TABLES, SHOW VIEW, TRIGGER, UPDATE, ALTER, GRANT OPTION, DROP
    ON Netflix.* TO 'senior'@'%';
GRANT SELECT ON mysql.proc TO 'senior'@'%';
