-- User creation

CREATE USER 'senior'@'%' IDENTIFIED BY 'password';
GRANT SELECT ON Netflix.* TO 'senior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Add_Media TO 'senior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Add_Profile TO 'senior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Add_Watchlist TO 'senior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Apply_Discount TO 'senior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Block_User TO 'senior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Remove_Media TO 'senior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Remove_Profile TO 'senior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Remove_User TO 'senior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Remove_Watchlist TO 'senior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Update_Currently_Watched TO 'senior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Update_Profile_Genre TO 'senior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.User_Login TO 'senior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Get_Media TO 'senior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Get_Profile TO 'senior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Get_Watchlist TO 'senior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Register_User TO 'senior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Update_Password TO 'senior'@'%';
FLUSH PRIVILEGES;

CREATE USER 'medior'@'%' IDENTIFIED BY 'password';
GRANT SELECT ON Netflix.Account TO 'medior'@'%';
GRANT SELECT ON Netflix.Genre TO 'medior'@'%';
GRANT SELECT ON Netflix.Language TO 'medior'@'%';
GRANT SELECT ON Netflix.Media TO 'medior'@'%';
GRANT SELECT ON Netflix.Media_Quality TO 'medior'@'%';
GRANT SELECT ON Netflix.Profile TO 'medior'@'%';
GRANT SELECT ON Netflix.Profile_Genre TO 'medior'@'%';
GRANT SELECT ON Netflix.Profile_Viewing_Classification TO 'medior'@'%';
GRANT SELECT ON Netflix.Profile_Watched_Media TO 'medior'@'%';
GRANT SELECT ON Netflix.Profile_Watch_List TO 'medior'@'%';
GRANT SELECT ON Netflix.Series TO 'medior'@'%';
GRANT SELECT ON Netflix.Subtitle TO 'medior'@'%';
GRANT SELECT ON Netflix.Viewing_Classification TO 'medior'@'%';
GRANT SELECT ON Netflix.Get_All_Genres_By_Views TO 'medior'@'%';
GRANT SELECT ON Netflix.Get_Watched_Media_By_Views TO 'medior'@'%';
GRANT SELECT ON Netflix.Get_Movies_By_Views TO 'medior'@'%';
GRANT SELECT ON Netflix.Get_Watched_Series_By_Views TO 'medior'@'%';
GRANT SELECT ON Netflix.Get_Bottom_Ten_Genres TO 'medior'@'%';
GRANT SELECT ON Netflix.Get_Bottom_Ten_Media TO 'medior'@'%';
GRANT SELECT ON Netflix.Get_Bottom_Ten_Movies TO 'medior'@'%';
GRANT SELECT ON Netflix.Get_Bottom_Ten_Series TO 'medior'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Longest_Series TO 'medior'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Shortest_Series TO 'medior'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Longest_Movies TO 'medior'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Shortest_Movies TO 'medior'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Watched_Genres TO 'medior'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Watched_Media TO 'medior'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Watched_Movies TO 'medior'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Watched_Series TO 'medior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Add_Media TO 'medior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Add_Profile TO 'medior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Add_Watchlist TO 'medior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Block_User TO 'medior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Remove_Media TO 'medior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Remove_Profile TO 'medior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Remove_User TO 'medior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Remove_Watchlist TO 'medior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Update_Currently_Watched TO 'medior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Update_Profile_Genre TO 'medior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.User_Login TO 'medior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Get_Media TO 'medior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Get_Profile TO 'medior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Get_Watchlist TO 'medior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Register_User TO 'medior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Update_Password TO 'medior'@'%';
FLUSH PRIVILEGES;

CREATE USER 'junior'@'%' IDENTIFIED BY 'password';
GRANT SELECT ON Netflix.Genre TO 'medior'@'%';
GRANT SELECT ON Netflix.Language TO 'medior'@'%';
GRANT SELECT ON Netflix.Media TO 'medior'@'%';
GRANT SELECT ON Netflix.Media_Quality TO 'medior'@'%';
GRANT SELECT ON Netflix.Profile TO 'medior'@'%';
GRANT SELECT ON Netflix.Profile_Genre TO 'medior'@'%';
GRANT SELECT ON Netflix.Profile_Viewing_Classification TO 'medior'@'%';
GRANT SELECT ON Netflix.Profile_Watched_Media TO 'medior'@'%';
GRANT SELECT ON Netflix.Profile_Watch_List TO 'medior'@'%';
GRANT SELECT ON Netflix.Series TO 'medior'@'%';
GRANT SELECT ON Netflix.Subtitle TO 'medior'@'%';
GRANT SELECT ON Netflix.Viewing_Classification TO 'medior'@'%';
GRANT SELECT ON Netflix.Get_All_Genres_By_Views TO 'junior'@'%';
GRANT SELECT ON Netflix.Get_Watched_Media_By_Views TO 'junior'@'%';
GRANT SELECT ON Netflix.Get_Movies_By_Views TO 'junior'@'%';
GRANT SELECT ON Netflix.Get_Watched_Series_By_Views TO 'junior'@'%';
GRANT SELECT ON Netflix.Get_Bottom_Ten_Genres TO 'junior'@'%';
GRANT SELECT ON Netflix.Get_Bottom_Ten_Media TO 'junior'@'%';
GRANT SELECT ON Netflix.Get_Bottom_Ten_Movies TO 'junior'@'%';
GRANT SELECT ON Netflix.Get_Bottom_Ten_Series TO 'junior'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Longest_Series TO 'junior'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Shortest_Series TO 'junior'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Longest_Movies TO 'junior'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Shortest_Movies TO 'junior'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Watched_Genres TO 'junior'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Watched_Media TO 'junior'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Watched_Movies TO 'junior'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Watched_Series TO 'junior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Add_Media TO 'junior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Add_Profile TO 'junior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Add_Watchlist TO 'junior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Block_User TO 'junior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Remove_Media TO 'junior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Remove_Profile TO 'junior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Remove_User TO 'junior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Remove_Watchlist TO 'junior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Update_Currently_Watched TO 'junior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Update_Profile_Genre TO 'junior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.User_Login TO 'junior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Get_Media TO 'junior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Get_Profile TO 'junior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Get_Watchlist TO 'junior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Register_User TO 'junior'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Update_Password TO 'junior'@'%';
FLUSH PRIVILEGES;

CREATE USER 'api'@'%' IDENTIFIED BY 'password';
GRANT SELECT ON Netflix.Get_All_Revenue TO 'api'@'%';
GRANT SELECT ON Netflix.Get_All_Genres_By_Views TO 'api'@'%';
GRANT SELECT ON Netflix.Get_Watched_Media_By_Views TO 'api'@'%';
GRANT SELECT ON Netflix.Get_Movies_By_Views TO 'api'@'%';
GRANT SELECT ON Netflix.Get_Watched_Series_By_Views TO 'api'@'%';
GRANT SELECT ON Netflix.Get_Amount_Of_Discounted_Users TO 'api'@'%';
GRANT SELECT ON Netflix.Get_Bottom_Ten_Genres TO 'api'@'%';
GRANT SELECT ON Netflix.Get_Bottom_Ten_Media TO 'api'@'%';
GRANT SELECT ON Netflix.Get_Bottom_Ten_Movies TO 'api'@'%';
GRANT SELECT ON Netflix.Get_Bottom_Ten_Series TO 'api'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Longest_Series TO 'api'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Shortest_Series TO 'api'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Longest_Movies TO 'api'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Shortest_Movies TO 'api'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Watched_Genres TO 'api'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Watched_Media TO 'api'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Watched_Movies TO 'api'@'%';
GRANT SELECT ON Netflix.Get_Top_Ten_Watched_Series TO 'api'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Add_Media TO 'api'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Add_Profile TO 'api'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Add_Watchlist TO 'api'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Apply_Discount TO 'api'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Block_User TO 'api'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Remove_Media TO 'api'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Remove_Profile TO 'api'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Remove_User TO 'api'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Remove_Watchlist TO 'api'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Update_Currently_Watched TO 'api'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Update_Profile_Genre TO 'api'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.User_Login TO 'api'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Get_Media TO 'api'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Get_Profile TO 'api'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Get_Watchlist TO 'api'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Register_User TO 'api'@'%';
GRANT EXECUTE ON PROCEDURE Netflix.Update_Password TO 'api'@'%';
FLUSH PRIVILEGES;

-- Drop root users (if they exist)
DROP USER IF EXISTS 'root'@'localhost';
DROP USER IF EXISTS 'root'@'%';

-- Flush privileges to apply changes
FLUSH PRIVILEGES;
