FROM node:16

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy all files, including the docker folder
COPY . .

# Make entrypoint.sh executable
RUN chmod +x /app/docker/entrypoint.sh

# Expose port 8080
EXPOSE 8080

# Run the entrypoint script
CMD ["/app/docker/entrypoint.sh"]